//自定义一个运行时期的异常类，并继承于java.lang.RuntimeException

package com._520it_exception;
//业务逻辑异常
public class LogicExceptionDemo extends RuntimeException {
	private static final long serialVersionUID = 5426152759533244574L;

	public LogicExceptionDemo() {
		super();
		// TODO Auto-generated constructor stub
	}

	public LogicExceptionDemo(String message, Throwable cause) {
		super(message, cause);
		// TODO Auto-generated constructor stub
	}

	public LogicExceptionDemo(String message) {
		super(message);
		// TODO Auto-generated constructor stub
	}
}


//模拟一个注册时用户名已经被注册然后抛出错误的案列(使用上面的自定义一个运行时期的异常类LogicExceptionDemo)
package com._520it_exception;
public class RegistorDemo {
	// 模拟数据库中已经存在的用户名
	private static String[] names = { "lucy", "tom", "will" };

	public static void main(String[] args) {
	
		try {
			checkName("will");
			System.out.println("注册成功");
		} catch (LogicExceptionDemo e) {
			// TODO: handle exception
			System.out.println(e.getMessage());
		}
	}
	//判断当前账号是否存在
	public static boolean checkName(String 	usename){
		for (String name : names) {
			if(name.equals(usename)){
				throw new LogicExceptionDemo("亲，"+name+",已经被注册了！");
			}
		}
		return true;
	}
}
